version: '2'

services:
  php:
    build: docker/php
    expose:
      - "9000"
    volumes:
      - ./:/app

  web:
    image: nginx:1.11
    ports:
      - "80:80"
    links:
      - php
    volumes:
      - ./:/app
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf